import * as React from "react";
import type { Metadata } from "next";
import { MarketingNav } from "@/components/marketing/nav";
import { MarketingFooter } from "@/components/marketing/footer";
import { getSessionUser, getCurrentProfile } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Privacy Policy — ForgeGuard AI",
  description:
    "ForgeGuard AI Privacy Policy. How we collect, use, and protect your data.",
};

const LAST_UPDATED = "May 15, 2025";

export default async function PrivacyPage() {
  const user = await getSessionUser();
  const isAuthenticated = !!user;
  let destination = "/dashboard";
  if (isAuthenticated) {
    const profile = await getCurrentProfile();
    if (profile?.role === "admin") destination = "/admin";
  }

  return (
    <main className="relative w-full">
      <MarketingNav session={{ isAuthenticated, destination }} />

      <div className="mx-auto max-w-3xl px-6 pt-32 pb-24 md:px-8">
        <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-acid mb-4">
          // legal/privacy
        </p>
        <h1 className="text-3xl font-bold text-foreground mb-2">Privacy Policy</h1>
        <p className="text-sm text-foreground-muted mb-12">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="space-y-10 text-sm leading-relaxed text-foreground-muted">
          <Section title="1. Overview">
            <p>
              ForgeGuard AI ("we", "us", "Platform") is a security research and
              red-teaming platform for AI systems. This Privacy Policy describes
              how we collect, use, store, and protect personal information in
              connection with your use of our Platform.
            </p>
            <p>
              We are committed to data minimization. We collect only what is
              necessary to operate the Platform securely and deliver the service
              you've signed up for.
            </p>
          </Section>

          <Section title="2. Information We Collect">
            <p className="font-medium text-foreground">Account data:</p>
            <ul className="mt-2 space-y-1.5 pl-4">
              <Bullet>Email address (required for authentication)</Bullet>
              <Bullet>Full name and display name (optional, user-provided)</Bullet>
              <Bullet>Professional role / access tier (Client, Hacker, Developer)</Bullet>
              <Bullet>Domain / organization (for corporate verification features)</Bullet>
              <Bullet>Phone number (optional, for two-factor authentication)</Bullet>
            </ul>

            <p className="font-medium text-foreground mt-6">Platform activity:</p>
            <ul className="mt-2 space-y-1.5 pl-4">
              <Bullet>Scan targets submitted (domain names, endpoints)</Bullet>
              <Bullet>Scan results and CVSS-scored reports generated by the engine</Bullet>
              <Bullet>Vulnerability reports submitted through the Bounty program</Bullet>
              <Bullet>Scripts published on the Bazaar</Bullet>
              <Bullet>Mission logs and red-team operation records</Bullet>
            </ul>

            <p className="font-medium text-foreground mt-6">Technical data:</p>
            <ul className="mt-2 space-y-1.5 pl-4">
              <Bullet>IP address (for rate limiting and abuse prevention)</Bullet>
              <Bullet>Browser type and operating system (for compatibility)</Bullet>
              <Bullet>Session tokens (stored in Supabase, never in localStorage)</Bullet>
              <Bullet>Click tracking on outreach links (for War Machine outreach campaigns — anonymized)</Bullet>
            </ul>
          </Section>

          <Section title="3. How We Use Your Data">
            <p>We use your data exclusively to:</p>
            <ul className="mt-3 space-y-1.5 pl-4">
              <Bullet>Authenticate and authorize your access to the Platform</Bullet>
              <Bullet>Deliver scan results, mission logs, and reports</Bullet>
              <Bullet>Process bounty reward payments via Payoneer or Wise</Bullet>
              <Bullet>Send transactional emails (scan complete, report triage, payment confirmation)</Bullet>
              <Bullet>Detect and prevent abuse, unauthorized scanning, and policy violations</Bullet>
              <Bullet>Improve the Platform's scan engine and attack taxonomy</Bullet>
            </ul>
            <p className="mt-4">
              We do not use your data for advertising, behavioral profiling, or
              third-party monetization of any kind.
            </p>
          </Section>

          <Section title="4. Data Storage and Security">
            <p>
              All Platform data is stored in Supabase, hosted on AWS
              infrastructure with SOC 2 Type II certification. Security
              measures include:
            </p>
            <ul className="mt-3 space-y-1.5 pl-4">
              <Bullet>Row-Level Security (RLS) on all Supabase tables — each user can only access their own data</Bullet>
              <Bullet>Scan payloads and results encrypted at rest using AES-256</Bullet>
              <Bullet>All AI API calls proxied through our Node.js server layer — your API keys never touch client code</Bullet>
              <Bullet>TLS 1.3 in transit for all data transfers</Bullet>
              <Bullet>Session tokens rotated on each request, invalidated on logout</Bullet>
              <Bullet>Service role keys restricted to server-only contexts, never exposed to the browser</Bullet>
            </ul>
          </Section>

          <Section title="5. Third-Party Services">
            <p>
              We use the following third-party services to operate the Platform.
              Each service has its own privacy policy governing their data use:
            </p>
            <div className="mt-4 space-y-3">
              {[
                { name: "Supabase", use: "Authentication, database, Realtime", link: "https://supabase.com/privacy" },
                { name: "Railway", use: "Python scan engine hosting", link: "https://railway.app/legal/privacy" },
                { name: "LemonSqueezy", use: "Subscription billing and payment processing", link: "https://www.lemonsqueezy.com/privacy" },
                { name: "Resend", use: "Transactional email delivery", link: "https://resend.com/privacy" },
                { name: "OpenRouter / Groq", use: "LLM API for scan engine and Forge", link: "https://openrouter.ai/privacy" },
                { name: "Vercel", use: "Next.js hosting and edge functions", link: "https://vercel.com/legal/privacy-policy" },
              ].map((s) => (
                <div
                  key={s.name}
                  className="flex items-start justify-between gap-4 rounded-sm border border-white/[0.04] bg-white/[0.02] px-4 py-3"
                >
                  <div>
                    <p className="font-medium text-foreground text-[13px]">{s.name}</p>
                    <p className="text-[12px] text-foreground-muted mt-0.5">{s.use}</p>
                  </div>
                  <a
                    href={s.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="shrink-0 text-[11px] text-acid/70 hover:text-acid"
                  >
                    Policy ↗
                  </a>
                </div>
              ))}
            </div>
          </Section>

          <Section title="6. Data Retention">
            <p>
              We retain your data for as long as your account is active. Upon
              account deletion:
            </p>
            <ul className="mt-3 space-y-1.5 pl-4">
              <Bullet>Account and profile data is deleted within 30 days</Bullet>
              <Bullet>Scan results associated with your account are anonymized or deleted</Bullet>
              <Bullet>Bounty reports that have been triaged and remediated may be retained in anonymized form for our vulnerability database</Bullet>
              <Bullet>Billing records are retained for 7 years as required by financial regulations</Bullet>
            </ul>
          </Section>

          <Section title="7. Your Rights">
            <p>
              Depending on your jurisdiction, you may have the following rights:
            </p>
            <ul className="mt-3 space-y-1.5 pl-4">
              <Bullet><strong className="text-foreground">Access:</strong> Request a copy of all personal data we hold about you</Bullet>
              <Bullet><strong className="text-foreground">Rectification:</strong> Correct inaccurate or incomplete personal data</Bullet>
              <Bullet><strong className="text-foreground">Erasure:</strong> Request deletion of your personal data ("right to be forgotten")</Bullet>
              <Bullet><strong className="text-foreground">Portability:</strong> Receive your data in a structured, machine-readable format</Bullet>
              <Bullet><strong className="text-foreground">Objection:</strong> Object to processing of your data for certain purposes</Bullet>
            </ul>
            <p className="mt-4">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:privacy@forgeguard.ai" className="text-acid hover:underline">
                privacy@forgeguard.ai
              </a>
              . We will respond within 30 days.
            </p>
          </Section>

          <Section title="8. Cookies">
            <p>
              We use minimal cookies strictly necessary for Platform operation:
            </p>
            <ul className="mt-3 space-y-1.5 pl-4">
              <Bullet>Session cookie (Supabase auth): stores your authentication token</Bullet>
              <Bullet>Theme preference cookie: stores your dark/light mode selection</Bullet>
            </ul>
            <p className="mt-4">
              We do not use advertising cookies, tracking pixels, or
              third-party analytics beyond essential operational telemetry.
            </p>
          </Section>

          <Section title="9. Changes to This Policy">
            <p>
              We may update this Privacy Policy to reflect changes in our
              practices or legal requirements. We will notify registered users
              of material changes via email at least 14 days before the changes
              take effect.
            </p>
          </Section>

          <Section title="10. Contact">
            <p>
              For privacy-related questions or to exercise your rights, contact:
            </p>
            <div className="mt-3 rounded-sm border border-white/[0.06] bg-white/[0.02] p-4">
              <p className="text-[13px] text-foreground">ForgeGuard AI — Data Protection</p>
              <a href="mailto:privacy@forgeguard.ai" className="text-[13px] text-acid hover:underline">
                privacy@forgeguard.ai
              </a>
            </div>
          </Section>
        </div>
      </div>

      <MarketingFooter />
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="mb-4 font-semibold text-foreground text-base border-b border-white/[0.06] pb-2">
        {title}
      </h2>
      <div className="space-y-4">{children}</div>
    </section>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2 text-foreground-muted">
      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-acid/50" />
      {children}
    </li>
  );
}
