import * as React from "react";
import { LegalSection, LegalBullet } from "@/components/legal/legal-section";

export function PrivacyContent() {
  return (
    <>
      <LegalSection title="1. Overview">
        <p>
          ForgeGuard AI (&quot;we&quot;, &quot;us&quot;, &quot;Platform&quot;) is a security research and
          red-teaming platform for AI systems. This Privacy Policy describes
          how we collect, use, store, and protect personal information in
          connection with your use of our Platform.
        </p>
        <p>
          We are committed to data minimization. We collect only what is
          necessary to operate the Platform securely and deliver the service
          you have signed up for.
        </p>
      </LegalSection>

      <LegalSection title="2. Information We Collect">
        <p className="font-medium text-foreground">Account data:</p>
        <ul className="mt-2 space-y-1.5 pl-4">
          <LegalBullet>Email address (required for authentication)</LegalBullet>
          <LegalBullet>Full name and display name (optional, user-provided)</LegalBullet>
          <LegalBullet>Professional role / access tier (Client, Hacker, Developer)</LegalBullet>
          <LegalBullet>Domain / organization (for corporate verification features)</LegalBullet>
          <LegalBullet>Phone number (optional, for two-factor authentication)</LegalBullet>
        </ul>

        <p className="mt-6 font-medium text-foreground">Platform activity:</p>
        <ul className="mt-2 space-y-1.5 pl-4">
          <LegalBullet>Scan targets submitted (domain names, endpoints)</LegalBullet>
          <LegalBullet>Scan results and CVSS-scored reports generated by the engine</LegalBullet>
          <LegalBullet>Vulnerability reports submitted through the Bounty program</LegalBullet>
          <LegalBullet>Scripts published on the Bazaar</LegalBullet>
          <LegalBullet>Mission logs and red-team operation records</LegalBullet>
        </ul>

        <p className="mt-6 font-medium text-foreground">Technical data:</p>
        <ul className="mt-2 space-y-1.5 pl-4">
          <LegalBullet>IP address (for rate limiting and abuse prevention)</LegalBullet>
          <LegalBullet>Browser type and operating system (for compatibility)</LegalBullet>
          <LegalBullet>Session tokens (stored in Supabase, never in localStorage)</LegalBullet>
          <LegalBullet>Cookie consent timestamp stored on your profile when you accept</LegalBullet>
        </ul>
      </LegalSection>

      <LegalSection title="3. How We Use Your Data">
        <p>We use your data exclusively to:</p>
        <ul className="mt-3 space-y-1.5 pl-4">
          <LegalBullet>Authenticate and authorize your access to the Platform</LegalBullet>
          <LegalBullet>Deliver scan results, mission logs, and reports</LegalBullet>
          <LegalBullet>Process bounty reward payments via Payoneer or Wise</LegalBullet>
          <LegalBullet>Send transactional emails (scan complete, report triage, payment confirmation)</LegalBullet>
          <LegalBullet>Detect and prevent abuse, unauthorized scanning, and policy violations</LegalBullet>
          <LegalBullet>Improve the Platform scan engine and attack taxonomy</LegalBullet>
        </ul>
        <p className="mt-4">
          We do not use your data for advertising, behavioral profiling, or
          third-party monetization of any kind.
        </p>
      </LegalSection>

      <LegalSection title="4. Data Storage and Security">
        <p>
          All Platform data is stored in Supabase, hosted on AWS
          infrastructure with SOC 2 Type II certification. Security measures
          include Row-Level Security (RLS), AES-256 disk encryption at rest,
          server-side credential sealing (AES-256-GCM where configured),
          TLS 1.3 in transit, and server-only service role keys.
        </p>
      </LegalSection>

      <LegalSection title="5. Third-Party Services">
        <p>
          We use Supabase (database and authentication), Railway (scan engine
          hosting), Lemon Squeezy (merchant of record for subscriptions and
          digital purchases), Resend (transactional email), OpenRouter/Groq
          (AI inference for identity audit and scan intelligence), and Vercel
          (application hosting). Each provider maintains its own privacy policy.
        </p>
        <p className="mt-3">
          Subscription payments ($49/month Startup, $199/month Enterprise) are
          processed by Lemon Squeezy. We do not store full card numbers on our
          servers.
        </p>
      </LegalSection>

      <LegalSection title="6. Data Retention">
        <p>We retain your data while your account is active. Upon account deletion request:</p>
        <ul className="mt-3 space-y-1.5 pl-4">
          <LegalBullet>Profile data is deleted within 30 days of your confirmed request</LegalBullet>
          <LegalBullet>Scan results are anonymized or deleted per retention policy</LegalBullet>
          <LegalBullet>Billing records may be retained up to 7 years where required by law</LegalBullet>
        </ul>
      </LegalSection>

      <LegalSection title="7. Your Rights and Account Deletion">
        <p>
          You may request access, rectification, portability, or erasure of your
          personal data. To delete your account, use{" "}
          <strong className="text-foreground">Delete Account</strong> in
          Dashboard → Settings. This sets a deletion request timestamp; we process
          erasure within 30 days and sign you out immediately.
        </p>
        <p className="mt-4">
          Contact{" "}
          <a href="mailto:privacy@forgeguard.ai" className="text-acid hover:underline">
            privacy@forgeguard.ai
          </a>{" "}
          for other rights requests. We respond within 30 days.
        </p>
      </LegalSection>

      <LegalSection title="8. Cookies and Consent">
        <p>We use essential cookies only:</p>
        <ul className="mt-3 space-y-1.5 pl-4">
          <LegalBullet>Session cookie (Supabase auth)</LegalBullet>
          <LegalBullet>Theme preference cookie</LegalBullet>
          <LegalBullet>Cookie consent record (`cookie_consent_at` on your profile, or `fg_cookie_consent` for guests)</LegalBullet>
        </ul>
        <p className="mt-4">
          Our cookie banner logs your agreement before non-essential features load.
          We do not use advertising cookies or third-party analytics trackers.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes to This Policy">
        <p>
          Material changes are communicated to registered users at least 14 days
          before they take effect.
        </p>
      </LegalSection>

      <LegalSection title="10. Contact">
        <div className="mt-3 rounded-sm border border-white/[0.06] bg-white/[0.02] p-4 font-mono text-[13px]">
          <p className="text-foreground">ForgeGuard AI — Data Protection</p>
          <a href="mailto:privacy@forgeguard.ai" className="text-acid hover:underline">
            privacy@forgeguard.ai
          </a>
        </div>
      </LegalSection>
    </>
  );
}
