/**
 * GET /api/track/[token]
 * ─────────────────────────────────────────────────────────────────────────────
 * Shadow Fleet Click Tracker — War Machine outreach link handler.
 *
 * When a lead clicks the CTA link in their cold email, they hit this route.
 * We:
 *   1. Look up the click_token in the leads table
 *   2. Update status → 'clicked', record clicked_at timestamp
 *   3. 301-redirect to forgeguard.ai (or a custom landing page)
 *
 * No auth required — the click_token is the shared secret.
 * The token is a UUID v4 (generated by Supabase on insert) so it's
 * unguessable and single-use in terms of tracking value.
 */

import { NextResponse, type NextRequest } from "next/server";
import { createClient }                    from "@supabase/supabase-js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const REDIRECT_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://forgeguard.ai";

// Use service role for this write — no RLS on leads table needed
function getAdminClient() {
  const url = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
  if (!url || !key) throw new Error("Supabase env vars not set");
  return createClient(url, key, { auth: { persistSession: false } });
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ token: string }> },
) {
  const { token } = await params;

  // Validate UUID format to block probing
  const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!token || !UUID_RE.test(token)) {
    return NextResponse.redirect(REDIRECT_URL, { status: 301 });
  }

  try {
    const sb = getAdminClient();

    // Only update if not already clicked (idempotent on re-clicks)
    const { data } = await sb
      .from("leads")
      .update({ status: "clicked", clicked_at: new Date().toISOString() })
      .eq("click_token", token)
      .neq("status", "clicked")          // don't double-count
      .select("company_name, website_url")
      .maybeSingle();

    if (data) {
      console.log(`[track] Click recorded: ${data.company_name} (${token.slice(0, 8)}…)`);
    }
  } catch (err) {
    // Never fail a redirect over a DB error — the lead already clicked
    console.error("[track] DB update failed:", err);
  }

  return NextResponse.redirect(REDIRECT_URL, { status: 301 });
}
