-- ============================================================
-- Sprint 9: Aegis Rules + Intelligence Hub Tables
-- ForgeGuard AI — 2026-05-17
-- ============================================================
-- Depends on: 0002_agathon_schema.sql (scans table)
--             20260517_sprint8_identity.sql (profiles.access_level)
-- ============================================================

-- ─── 1. aegis_rules ────────────────────────────────────────
-- Stores WAF rules exported from completed scans via
-- POST /api/aegis/export. Persisted for cross-reference in
-- Bounty Vault triage (AegisCoverage).

CREATE TABLE IF NOT EXISTS aegis_rules (
  id          bigserial   PRIMARY KEY,
  scan_id     uuid        NOT NULL REFERENCES scans (id) ON DELETE CASCADE,
  rule_id     text        NOT NULL UNIQUE,          -- fg-aegis-<technique>-<ts36>
  pattern     text        NOT NULL,                 -- WAF expression (truncated at 500 chars)
  description text        NOT NULL,
  action      text        NOT NULL CHECK (action IN ('block', 'challenge', 'log')),
  format      text        NOT NULL DEFAULT 'cloudflare'
                                   CHECK (format IN ('cloudflare', 'python')),
  enabled     boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  aegis_rules             IS 'WAF rules auto-generated by Aegis Defense export from scan findings';
COMMENT ON COLUMN aegis_rules.rule_id     IS 'Stable unique ref: fg-aegis-<technique>-<ts36>. Used as upsert key.';
COMMENT ON COLUMN aegis_rules.pattern     IS 'Cloudflare WAF expression or Python regex (≤500 chars)';
COMMENT ON COLUMN aegis_rules.format      IS 'Target platform: cloudflare | python';

CREATE INDEX IF NOT EXISTS idx_aegis_rules_scan_id  ON aegis_rules (scan_id);
CREATE INDEX IF NOT EXISTS idx_aegis_rules_enabled   ON aegis_rules (enabled) WHERE enabled = true;

-- Updated-at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aegis_rules_updated_at ON aegis_rules;
CREATE TRIGGER trg_aegis_rules_updated_at
  BEFORE UPDATE ON aegis_rules
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- RLS: users can only see rules from their own scans
ALTER TABLE aegis_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own aegis_rules"
  ON aegis_rules FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM scans s
       WHERE s.id = aegis_rules.scan_id
         AND s.user_id = auth.uid()
    )
  );

-- Writes go through service-role (admin client) in API routes.
-- No INSERT/UPDATE policy for authenticated role.


-- ─── 2. intel_messages ─────────────────────────────────────
-- Community chat messages for the Intelligence Hub.
-- Populated and subscribed to via Supabase Realtime on the
-- /dashboard/intel page. Each row is a single chat message.

CREATE TABLE IF NOT EXISTS intel_messages (
  id          bigserial   PRIMARY KEY,
  user_id     uuid        NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  content     text        NOT NULL CHECK (char_length(content) BETWEEN 1 AND 500),
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  intel_messages          IS 'Real-time community chat messages for the Intelligence Hub';
COMMENT ON COLUMN intel_messages.content  IS 'Message body, 1–500 characters';

-- Fast retrieval of recent messages (last N by time)
CREATE INDEX IF NOT EXISTS idx_intel_messages_created_at ON intel_messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intel_messages_user_id    ON intel_messages (user_id);

-- RLS: authenticated users can read all messages + insert their own
ALTER TABLE intel_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users read intel_messages"
  ON intel_messages FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users insert own intel_messages"
  ON intel_messages FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- No UPDATE / DELETE for regular users — messages are immutable once sent.
-- Admins (service role) bypass RLS by default.


-- ─── 3. Enable Realtime on intel_messages ──────────────────
-- Supabase Realtime must have the table in the publication.
-- Run this once; idempotent thanks to IF NOT EXISTS / OR REPLACE.

ALTER PUBLICATION supabase_realtime ADD TABLE intel_messages;


-- ─── 4. Helper view: intel_messages_with_profile ───────────
-- Joins messages with display names so the chat UI gets the
-- sender's handle without a separate profile query per message.

CREATE OR REPLACE VIEW intel_messages_with_profile AS
SELECT
  m.id,
  m.user_id,
  m.content,
  m.created_at,
  COALESCE(p.full_name, p.username, 'Anonymous') AS display_name
FROM intel_messages m
LEFT JOIN profiles p ON p.id = m.user_id;

COMMENT ON VIEW intel_messages_with_profile IS 'Intel Hub chat messages enriched with sender display name';

-- RLS on the view is inherited from intel_messages (underlying table).
